// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/education-hub/BE/app/entities"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// SchoolRepo is an autogenerated mock type for the SchoolRepo type
type SchoolRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: db, school
func (_m *SchoolRepo) Create(db *gorm.DB, school entities.School) (int, error) {
	ret := _m.Called(db, school)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.School) (int, error)); ok {
		return rf(db, school)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.School) int); ok {
		r0 = rf(db, school)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, entities.School) error); ok {
		r1 = rf(db, school)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNPSN provides a mock function with given fields: db, npsn
func (_m *SchoolRepo) FindByNPSN(db *gorm.DB, npsn string) error {
	ret := _m.Called(db, npsn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(db, npsn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: db, school
func (_m *SchoolRepo) Update(db *gorm.DB, school entities.School) (*entities.School, error) {
	ret := _m.Called(db, school)

	var r0 *entities.School
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.School) (*entities.School, error)); ok {
		return rf(db, school)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, entities.School) *entities.School); ok {
		r0 = rf(db, school)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.School)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, entities.School) error); ok {
		r1 = rf(db, school)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSchoolRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewSchoolRepo creates a new instance of SchoolRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSchoolRepo(t mockConstructorTestingTNewSchoolRepo) *SchoolRepo {
	mock := &SchoolRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
