// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	user "github.com/education-hub/BE/app/entities/user"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: db, _a1
func (_m *UserRepo) Create(db *gorm.DB, _a1 user.User) error {
	ret := _m.Called(db, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, user.User) error); ok {
		r0 = rf(db, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: db, email
func (_m *UserRepo) FindByEmail(db *gorm.DB, email string) (*user.User, error) {
	ret := _m.Called(db, email)

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) (*user.User, error)); ok {
		return rf(db, email)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *user.User); ok {
		r0 = rf(db, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = rf(db, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUsername provides a mock function with given fields: db, username
func (_m *UserRepo) FindByUsername(db *gorm.DB, username string) (*user.User, error) {
	ret := _m.Called(db, username)

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) (*user.User, error)); ok {
		return rf(db, username)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *user.User); ok {
		r0 = rf(db, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = rf(db, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertForgotPassToken provides a mock function with given fields: db, req
func (_m *UserRepo) InsertForgotPassToken(db *gorm.DB, req user.ForgotPass) error {
	ret := _m.Called(db, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, user.ForgotPass) error); ok {
		r0 = rf(db, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetPass provides a mock function with given fields: db, newpass, token
func (_m *UserRepo) ResetPass(db *gorm.DB, newpass string, token string) error {
	ret := _m.Called(db, newpass, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string, string) error); ok {
		r0 = rf(db, newpass, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyEmail provides a mock function with given fields: db, verificationcode
func (_m *UserRepo) VerifyEmail(db *gorm.DB, verificationcode string) error {
	ret := _m.Called(db, verificationcode)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(db, verificationcode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepo(t mockConstructorTestingTNewUserRepo) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
